# Generated by Django 4.2.27 on 2026-02-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_appointment_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='next_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
