# Generated by Django 4.2.28 on 2026-02-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_blooddonor_next_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
        migrations.AddField(
            model_name='complaint',
            name='type_of_complaint',
            field=models.CharField(choices=[('service', 'Service'), ('staff', 'Staff'), ('facility', 'Facility'), ('billing', 'Billing'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
