# Generated by Django 4.2.28 on 2026-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_remove_complaint_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='ComplaintImage',
        ),
    ]
