# Generated by Django 5.0.14 on 2026-02-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_add_subject_to_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrecord',
            name='donation_type',
        ),
    ]
