# Generated by Django 5.1.3 on 2025-10-23 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('qualification', models.CharField(default='', max_length=150)),
                ('experience', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('utype', models.CharField(default='doctor', max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors')),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='doctors_id')),
                ('is_approved', models.BooleanField(default=False)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meditrackapp.department')),
            ],
        ),
    ]
