# Generated by Django 5.1.3 on 2025-10-23 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0002_department_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meditrackapp.department'),
        ),
    ]
