# Generated by Django 5.1.3 on 2025-10-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0004_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(default='', max_length=200),
        ),
    ]
