# Generated by Django 5.1.3 on 2025-10-27 07:09

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0006_alter_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=100),
        ),
    ]
