# Generated by Django 5.1.3 on 2025-11-04 08:07

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0007_doctor_working_days'),
        ('userapp', '0003_appointment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='op_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='userapp.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Number of times per day')),
                ('time_of_day', multiselectfield.db.fields.MultiSelectField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=100)),
                ('food_instruction', models.CharField(choices=[('before_food', 'Before Food'), ('after_food', 'After Food')], max_length=20)),
                ('number_of_days', models.PositiveIntegerField(default=1)),
                ('dosage', models.CharField(blank=True, help_text='e.g., 1 tablet, 5 ml, etc.', max_length=50, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='meditrackapp.prescription')),
            ],
        ),
    ]
