# Generated by Django 4.2.27 on 2026-01-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0017_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reschedulerequest',
            name='rescheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning (06:00 - 14:00)'), ('evening', 'Evening (14:00 - 22:00)'), ('all_day', 'All Day')], default='all_day', max_length=10),
        ),
    ]
