# Generated by Django 4.2.27 on 2026-01-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0019_blooddonationadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard Admin',
                'verbose_name_plural': 'Dashboard Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('meditrackapp.admin',),
        ),
    ]
