# Generated by Django 4.2.28 on 2026-02-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0020_dashboardadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='total_tokens',
            field=models.PositiveIntegerField(default=40, help_text='Total tokens per day (split equally between morning and afternoon)'),
        ),
    ]
