# Generated by Django 5.0.14 on 2026-02-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0021_doctor_total_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='afternoon_token_limit',
            field=models.PositiveIntegerField(default=20, help_text='Maximum tokens for the afternoon session'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='morning_token_limit',
            field=models.PositiveIntegerField(default=20, help_text='Maximum tokens for the morning session'),
        ),
    ]
