# Generated by Django 5.0.14 on 2026-02-24 08:41

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0022_doctor_afternoon_token_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='donation_type',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('monday', 'Mon'), ('tuesday', 'Tue'), ('wednesday', 'Wed'), ('thursday', 'Thu'), ('friday', 'Fri'), ('saturday', 'Sat'), ('sunday', 'Sun')], max_length=100),
        ),
    ]
